Mb UI ld 87 adventure time castle
BuildingaMaster/AdventureGame pull request #30
Opened 2023-12-01 20:00 UTC by BuildingaMaster

Look @ room descriptions... also cannot enter castle even when knight is killed

2023-12-02 22:55 UTC, jfduedu requested changes
Castle foundation looks good, but some rooms contain things we currently don't have. 
In this state, it is not mergeable at this time, so I will be marking this as a draft.

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "",
Missing alt description

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "",
Missing alt description

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "RoomName": "Ogor",
```suggestion
            "RoomName": "Ogre",
```

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "RoomDesc": "You come face to face with a fat, ugly, Ogor. \nIt's eyes are crossed, he swings a big club towards you and you don't even have to move. \nYou hear the wind of the swing move
```suggestion
            "RoomDesc": "You come face to face with a fat, ugly, ogre. \nIt's eyes are crossed, he swings a big club towards you and you don't even have to move. \nYou hear the wind of the swing move past you as it blows through your hair.\n\nThe ogre screams, \"AH AH AHHHHH\" and slams the club on the ground.\nHe is challanging you to fight.\n\n",
```

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "You come face to face with a fat, ugly, Ogor. \nIt's eyes are crossed, he swings a big club towards you and you don't even have to move. \nHe is challanging you to fight.
Should be different. Also, NPC map should mention if a enemy is in the room.

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "RoomDesc": "Panting from killing the Ogor, your eye catches armor a man could only dream of wearing.\nThe Diamond Armour reflects the and glimmers in the light.\n\"Only Kings and Queens
```suggestion
            "RoomDesc": "Panting from killing the ogre, your eye catches armor a man could only dream of wearing.\nYou see your reflection in The Diamond Armor, which glimmers in the light.\n\"Only Kings and Queens have the money to obtain this!\" you state in awe.\n",
```
The text wraps around the terminal making it difficult to read, consider adding new lines or making the description smaller.

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "Panting from killing the Ogor, your eye catches the best armour a man could equip.\nThe Diamond Armour reflects the light.",
```suggestion
            "AltRoomDesc": "The room of The Diamond Armour.",
```

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "RoomDesc": "You come to the end of the hall. \nThere are stairs to the left that lead up towards: \"HA HA HA HA\"\nTo your right are stairs that lead down to a dark, urky vibe.\nThere is
```suggestion
            "RoomDesc": "You come to the end of the hall. \nThere are stairs to the left that lead up towards: \"HA HA HA HA\"\nTo your right are stairs that lead down to a dark, urky vibe.\nThere is a sign above: \"Ain't No Church In The Wild.\"",
```

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "You come to the end of the hall. \nThere are stairs to the left that lead up towards a laugh, \"HA HA HA HA\"\nTo your right are stairs that lead down to a dark, urky plac
```suggestion
            "RoomDesc": "You come to the end of the hall. \nThere are stairs to the left that lead up towards: \"HA HA HA HA\"\nTo your right are stairs that lead down to a dark, urky vibe.\nThere is a sign above: \"Ain't No Church In The Wild.\"",
```

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "RoomDesc": "You grab a torch to see.\nEvery step you take down the stone stairs echoes.\nWater drops from the ceiling into puddles.\nYou see a rat run across the floor with a finger.",
```suggestion
            "RoomDesc": "Every step you take down the stone stairs echoes.\nWater drops from the ceiling into puddles.\nYou see a rat run across the floor with a finger.",
```
Is a torch going to be an item? If so, the item map will tell the player.

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "You grab a torch to see.\nEvery footstep echoes.",
```suggestion
            "AltRoomDesc": "Every footstep echoes.",
```
Is a torch going to be an item? If so, the item map will tell the player.

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "RoomDesc": "You faintly see a large, scaley creature sleeping with blood, skulls, and bones all around it's cage. \nYou can feel his power. ",
```suggestion
            "RoomDesc": "You faintly see a large, scaley creature lying on the ground with blood, skulls, and bones all around it's cage. \nYou can feel his power. ",
```
Just in case the dragon is already dead.

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "You faintly see a large, scaley creature sleeping with blood, skulls, and bones all around it's cage. \nYou can feel his power. ",
```suggestion
            "AltRoomDesc": "You faintly see a large, scaley creature laying on he ground with blood, skulls, and bones all around it's cage. \nYou can feel his power. ",
```
Just in case the dragon is already dead.

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "RoomDesc": "You shine your torch up to the steel cell and the creature opens one eye that stares through your soul.\nYou jump back and crush a skull. \nTHE DRAGON AWAKES IN RAGE!\n\nThe
```suggestion
            "RoomDesc": "You shine your torch up to the steel cell and the creature opens one eye that stares through your soul.\nYou jump back and crush a skull.",
```
NPCmap should handle this for you.

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "You jump back and crush a skull. \nTHE DRAGON AWAKES IN RAGE!\nTime to fight!",
```suggestion
            "AltRoomDesc": "Clumsily step back and crush yet another skull.\nAre you doing this on purpose?",
```

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +        },
This says you climb above but you go East?

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "In the distance, at the end of the hallway is a large figure sitting in a King's chair.\nLaughing \"AH HA HA HA HA\"\nA girl is chained and is struggling to escape, \"Some
Since this is the alt room description, maybe something like:

```suggestion
            "AltRoomDesc": "You still hear the booming laughter, and the rattling of the chains.",
```

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "",
Missing altroomdesc

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "You are getting closer to the large figure, he exclaims to the woman, \"You are hopeless, no one wants to save you! HA HA HA HA\"",
```suggestion
            "AltRoomDesc": "The figure is VERY close...",
```

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "",
Missing altroomdesc

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "The large figure is in rage, \"How did you get here?! \nYou have been banned from this kingdom, never to step foot in the Castle of Orina for eternity! \nOrdered to be exe
Needs different altroomdesc

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "\"King Zeus\" you state.\n\nKing Zeus: \"Remember what happened last time you tested me!\"\n\nYou: \"I have gotten stronger, no longer afraid of you!\"\n\nKing Zeus: \"I w
Needs different altroomdesc

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "",
Missing Altroomdesc. WIP?

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "RoomDesc": "The Fight!",
Missing roomdesc. WIP?

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "RoomDesc": "THIS ROOM CAN ONLY BE ENTERED IF BOSS IS DEFEATED OR DRAGON IS DEFEATED ",
WIP?

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "",
Missing Altroomdesc.

2023-12-02 22:55 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "RoomDesc": "You walk through the hall and approach the giggles.\nA blonde lady with a flower crown stops you in your tracks. \nShe says, \"I've missed you! Let's celebrate.\"\nYou look a
```suggestion
            "RoomDesc": "You walk through the hall and approach the giggles.\nA blonde lady with a flower crown stops you in your tracks. \nShe says, \"I've missed you! Let's celebrate.\"\nYou look at her confused and think \"I've never met this woman before.\"\nShe puts out an open hand and offers you a mushroom.\n\nAUTO TEXT SCRAMBLED MUSHROOM AND DAMAGE TAKEN",
```

2023-12-05 16:20 UTC, jfduedu requested changes
Small changes

2023-12-05 16:20 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "RoomDesc": "Thadeus gives Florence a kiss, then smiles at you.\nYou clench your fist and your face turns red. \nThadeus smirks at you and says, \"Come get some you coinless hobbit\" \n\n
```suggestion
            "RoomDesc": "Thadeus gives Florence a kiss, then smiles at you.\nYou clench your fist and your face turns red. \nThadeus smirks at you and says, \"Come get some you coinless hobbit!\" \n\nYou scream \"AHHHHH\" and run full speed towards Thadeus. ",
```

2023-12-05 16:20 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "RoomDesc": "The large figure is close enough to recgonize... \"King Thadeus!\" you roar.\nKing Thadeus is in rage, \"How did you get here?! \nYou have been banned from this kingdom, neve
```suggestion
            "RoomDesc": "The large figure is close enough to recognize... \"King Thadeus!\" you roar.\nKing Thadeus is in rage, \"How did you get here?! \nYou have been banned from this kingdom, never to step foot in the Castle of Orina for eternity! \nOrdered to be executed and humiliated!\"\n\nFlorence gasps, speechless. ", 
```

2023-12-05 16:20 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "You walk into a room full of pictures and flowers. \nYou find a picture of you and your lost love Florence! \nA wave of energy runs through your veins\nThe picture right n
```suggestion
            "AltRoomDesc": "You walk into a room full of pictures and flowers. \nYou find a picture of you and your lost love Florence! \nA wave of energy runs through your veins.\nThe picture right next to that is of the large figure and Florence.\nThey look happily together.\nYou pace the room in rage.", 
```

2023-12-05 16:20 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "RoomDesc": "You walk into a room full of pictures and flowers. \nYou come across a picture that grabs your attention\nThe picture is of you and your lost love Florence! \nYou think to yo
```suggestion
            "RoomDesc": "You walk into a room full of pictures and flowers. \nYou come across a picture that grabs your attention.\nThe picture is of you and your lost love Florence! \nYou think to yourself, \"She never forgot me!\" \nA wave of energy runs through your veins\nThis energy is shortly lived, the picture next to that is of the large figure and Florence.\nThey look happily together.\nYou pace the room in rage.",
```

2023-12-05 16:20 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "You are getting closer to the large figure.\nHe says to the lady, \n\"You are mine for eternity, your last boyfriend was a PEASANT! HA HA HA HA\"\n\nNorth, a room with bri
```suggestion
            "AltRoomDesc": "You are getting closer to the large figure.\nHe says to the lady, \n\"You are mine for eternity, your last boyfriend was a PEASANT! HA HA HA HA\"\n\nDue  north,  you can see a room with bright colors and pictures from the past.\n",
```

2023-12-05 16:20 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "RoomDesc": "You are getting closer to the large figure.\nHe charmingly says to the lady, \n\"You are mine for eternity, your last boyfriend was a PEASANT! HA HA HA HA\"\nYou try to pay n
```suggestion
            "RoomDesc": "You are getting closer to the large figure.\nHe charmingly says to the lady, \n\"You are mine for eternity, your last boyfriend was a PEASANT! HA HA HA HA\"\nYou try to pay no mind to his words.\n\nDue north, you see a room full of bright colors and pictures that intrigue you. ",
```

2023-12-05 16:20 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "A bunch of degenerate folks  turn your way.\nThey look like they haven't seen the sun in days.\nTheir eyes are bloodshot, hair looking crazy.\n",
```suggestion
            "AltRoomDesc": "A bunch of degenerate folks turn your way.\nThey look like they haven't seen the sun in days.\nTheir eyes are bloodshot, hair looking crazy.\n", 
```
Also, are they hostile?

2023-12-05 16:20 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "In the distance west, a large figure sitting in a King's chair.\nLaughing \"AH HA HA HA HA\"\nA girl is sitting on the large figure's lap. \n\nNorth, a room of people sitt
```suggestion
            "AltRoomDesc": "In the west, you see a large figure sitting in a King's chair.\nIt's booming laughter can be heard throughout the chambers.\nA girl is sitting on the large figure's lap. \n\nDue north, a room of people sitting at a table.\n",
```

2023-12-05 16:20 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "RoomDesc": "In the distance west, at the end of the hallway is a large figure sitting in a King's chair.\nLaughing \"AH HA HA HA HA\"\nA girl is sitting on the large figure's lap. \nYour
```suggestion
            "RoomDesc": "In the distance west, at the end of the hallway is a large figure sitting in a King's chair.\nIt's booming laughter can be heard throughout the chambers.\nA girl is sitting on the large figure's lap. \nYour eyes widen, you recognize that voice!\n\nNorth, a room of people huddled at a round table.",
```

2023-12-05 16:20 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "RoomDesc": "You look down and see dead gatekeepers, many missing limbs, blood oozing from them.\nThey all coincidentally have burn scars. \nOne gatekeeper opens his eyes and tries to mus
```suggestion
            "RoomDesc": "You look down and see dead gatekeepers, many missing limbs, blood oozing from them.\nThey all coincidentally have burn scars. \nOne gatekeeper opens his eyes and tries to muster the strength to talk, but all that comes out is \"Hel...\" and then his eyes close, lifeless.\n",
```

2023-12-05 16:20 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "A blonde lady with a flower crown stops you in your tracks. \nShe says, \"I've missed you! Let's celebrate.\"\nShe puts out an open hand and offers you a mushroom.\n\nWest
No change needed now, but that should probably use NPC dialog once implemented (I have an idea for it).

2023-12-05 16:50 UTC, BuildingaMaster commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "A bunch of degenerate folks  turn your way.\nThey look like they haven't seen the sun in days.\nTheir eyes are bloodshot, hair looking crazy.\n",
No, just people who you wouldn't want to hangout with, unless you want to make them hostile

2023-12-05 16:54 UTC, jfduedu commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "A bunch of degenerate folks  turn your way.\nThey look like they haven't seen the sun in days.\nTheir eyes are bloodshot, hair looking crazy.\n",
OK, sounds good

2023-12-05 16:56 UTC, BuildingaMaster commented on MasterForge/newmap.mfw
> +            "RoomDesc": "Thadeus gives Florence a kiss, then smiles at you.\nYou clench your fist and your face turns red. \nThadeus smirks at you and says, \"Come get some you coinless hobbit\" \n\n
Done

2023-12-05 16:56 UTC, BuildingaMaster commented on MasterForge/newmap.mfw
> +            "RoomDesc": "The large figure is close enough to recgonize... \"King Thadeus!\" you roar.\nKing Thadeus is in rage, \"How did you get here?! \nYou have been banned from this kingdom, neve
Done

2023-12-05 16:56 UTC, BuildingaMaster commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "You walk into a room full of pictures and flowers. \nYou find a picture of you and your lost love Florence! \nA wave of energy runs through your veins\nThe picture right n
Done

2023-12-05 16:56 UTC, BuildingaMaster commented on MasterForge/newmap.mfw
> +            "RoomDesc": "You walk into a room full of pictures and flowers. \nYou come across a picture that grabs your attention\nThe picture is of you and your lost love Florence! \nYou think to yo
Done

2023-12-05 16:56 UTC, BuildingaMaster commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "You are getting closer to the large figure.\nHe says to the lady, \n\"You are mine for eternity, your last boyfriend was a PEASANT! HA HA HA HA\"\n\nNorth, a room with bri
Done

2023-12-05 17:02 UTC, BuildingaMaster commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "In the distance west, a large figure sitting in a King's chair.\nLaughing \"AH HA HA HA HA\"\nA girl is sitting on the large figure's lap. \n\nNorth, a room of people sitt
Done

2023-12-05 17:03 UTC, BuildingaMaster commented on MasterForge/newmap.mfw
> +            "RoomDesc": "In the distance west, at the end of the hallway is a large figure sitting in a King's chair.\nLaughing \"AH HA HA HA HA\"\nA girl is sitting on the large figure's lap. \nYour
Done

2023-12-05 17:05 UTC, BuildingaMaster commented on MasterForge/newmap.mfw
> +            "RoomDesc": "You look down and see dead gatekeepers, many missing limbs, blood oozing from them.\nThey all coincidentally have burn scars. \nOne gatekeeper opens his eyes and tries to mus
Done

2023-12-05 17:06 UTC, BuildingaMaster commented on MasterForge/newmap.mfw
> +            "AltRoomDesc": "A blonde lady with a flower crown stops you in your tracks. \nShe says, \"I've missed you! Let's celebrate.\"\nShe puts out an open hand and offers you a mushroom.\n\nWest
Okay sounds good

2023-12-06 17:05 UTC, jfduedu approved these changes
OK

2023-12-06 17:05 UTC, merged